### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by noog** [OpenJabNab/OpenJabNab#32]
i have this error when i launch the command : make

 ztamp.h:106:1:   required from here
/usr/include/qt/QtCore/qmetatype.h:1330:59: erreur: ‘QObject’ is an inaccessible base of ‘Ztamp’
         enum { Value = sizeof(checkType(static_cast<T*>(0))) == sizeof(yes_type) };
                                                           ^
/usr/include/qt/QtCore/qmetatype.h: In instantiation of ‘struct QtPrivate::IsPointerToTypeDerivedFromQObject<Bunny*>’:
/usr/include/qt/QtCore/qmetatype.h:1543:69:   required from ‘struct QtPrivate::QMetaTypeTypeFlags<Bunny*>’
/usr/include/qt/QtCore/qmetatype.h:1591:71:   required from ‘int qRegisterNormalizedMetaType(const QByteArray&, T*, typename QtPrivate::MetaTypeDefinedHelper<T, (QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = Bunny*; typename QtPrivate::MetaTypeDefinedHelper<T, (QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType = QtPrivate::MetaTypeDefinedHelper<Bunny*, true>::DefinedType]’
/usr/include/qt/QtCore/qmetatype.h:1628:77:   required from ‘int qRegisterMetaType(const char*, T*, typename QtPrivate::MetaTypeDefinedHelper<T, (QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = Bunny*; typename QtPrivate::MetaTypeDefinedHelper<T, (QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType = QtPrivate::MetaTypeDefinedHelper<Bunny*, true>::DefinedType]’
bunny.h:212:1:   required from here
/usr/include/qt/QtCore/qmetatype.h:1330:59: erreur: ‘QObject’ is an inaccessible base of ‘Bunny’
Makefile:503 : la recette pour la cible « tmp/obj/httphandler.o » a échouée
make[1]: *** [tmp/obj/httphandler.o] Erreur 1
make[1] : on quitte le répertoire « /home/gael/Downloads/openjabnab/OpenJabNab/server/lib »
Makefile:45 : la recette pour la cible « sub-lib-make_first-ordered » a échouée
make: *** [sub-lib-make_first-ordered] Erreur 2

**Comment by RedoXPS** [comment]
Hi,

I think it's because you are trying to compile with Qt5; at least, that's how I could reproduce the error. OpenJabNab was developped with Qt4...

Try the following (works on Archlinux):

    cd OpenJabNab/server
    qmake-qt4 -r
    make

or maybe 

    cd OpenJabNab/server
    qt4-qmake -r
    make
